from dataclasses import dataclass

#
# Data Ingestion Artifact
@dataclass
class DataIngestionArtifact:
    """
    Artifact generated by the Data Ingestion component.
    
    Attributes:
        trained_file_path (str): Path to the training dataset CSV file.
        test_file_path (str): Path to the testing dataset CSV file.
    """
    trained_file_path: str
    test_file_path: str

# Data Validation Artifact
@dataclass
class DataValidationArtifact:
    """
    Artifact generated by Data Validation component.
    
    Attributes:
        validation_status (bool): True if validation passed, False otherwise.
        valid_train_file_path (str): Path to validated training data.
        valid_test_file_path (str): Path to validated test data.
        invalid_train_file_path (str): Path to rejected training data (if any).
        invalid_test_file_path (str): Path to rejected test data (if any).
        drift_report_file_path (str): Path to dataset drift report (YAML).
    """
    validation_status: bool
    valid_train_file_path: str
    valid_test_file_path: str
    invalid_train_file_path: str
    invalid_test_file_path: str
    drift_report_file_path: str

# Data Transformation Artifact
@dataclass
class DataTransformationArtifact:
    """
    Artifact generated by Data Transformation component.
    
    Attributes:
        transformed_object_file_path (str): Path to saved preprocessing object (e.g., KNN imputer pipeline).
        transformed_train_file_path (str): Path to transformed training dataset (NumPy array).
        transformed_test_file_path (str): Path to transformed test dataset (NumPy array).
    """
    transformed_object_file_path: str
    transformed_train_file_path: str
    transformed_test_file_path: str

# Classification Metrics Artifact
@dataclass
class ClassificationMetricArtifact:
    """
    Metrics artifact generated after evaluating a model.
    
    Attributes:
        f1_score (float): F1 score of the model.
        precision_score (float): Precision score of the model.
        recall_score (float): Recall score of the model.
    """
    f1_score: float
    precision_score: float
    recall_score: float

# Model Trainer Artifact
@dataclass
class ModelTrainerArtifact:
    """
    Artifact generated after training a model.
    
    Attributes:
        trained_model_file_path (str): Path to saved trained model.
        train_metric_artifact (ClassificationMetricArtifact): Metrics on training data.
        test_metric_artifact (ClassificationMetricArtifact): Metrics on testing data.
    """
    trained_model_file_path: str
    train_metric_artifact: ClassificationMetricArtifact
    test_metric_artifact: ClassificationMetricArtifact
