from dataclasses import dataclass

@dataclass
class DataIngestionArtifact:
    """artifact generated by Data Ingestion component"""
    trained_file_path:str
    test_file_path:str

@dataclass
class DataValidationArtifact:
    """artifact generated by Data Validation"""
    validation_status: bool
    valid_train_file_path: str
    valid_test_file_path: str
    invalid_train_file_path: str
    invalid_test_file_path: str
    drift_report_file_path: str

@dataclass
class DataTransformationArtifact:
    """artifact geerated by Data Transformation"""
    transformed_object_file_path: str
    transformed_train_file_path: str
    transformed_test_file_path: str

# @dataclass
# class ClassificationMetricArtifact:
#     """artifact generated after evaluation of the model"""
#     f1_score: float
#     precision_score: float
#     recall_score: float
    
# @dataclass
# class ModelTrainerArtifact:
#     """artifact generated after tranung a model"""
#     trained_model_file_path: str
#     train_metric_artifact: ClassificationMetricArtifact
#     test_metric_artifact: ClassificationMetricArtifact
